bird2: replace gcc flag workaround with patch fixing alignment issues
openwrt/routing pull request #1097
Opened 2024-12-17 23:20 UTC by PolynomialDivision

Previously, we used the -mno-unaligned-access flag to instruct GCC to forbid unaligned memory access on arm processors. This was a workaround for alignment issues that caused crashes.

This commit imports a patch from the BIRD mailing list discussion [0] that resolves the alignment issue by modifying the net_addr structure, removing the need for the GCC flag. The patch addresses the alignment problem more efficiently and avoids the performance, code size, and hardware optimization drawbacks of the flag.

[0] - http://trubka.network.cz/pipermail/bird-users/2024-December/017957.html

Maintainer: @tohojo 
Compile tested: arm7
Run tested: arm7

2024-12-18 18:31 UTC, tohojo requested changes
Needs PKG_RELEASE bump...

2024-12-18 21:56 UTC, spolack commented
Seems it was fixed upstream...
https://gitlab.nic.cz/labs/bird/-/commit/161aef353a56532752d5d0f97e432c0915058050

2024-12-19 17:45 UTC, tohojo commented
There are two patches upstream, let's include both - cf: http://trubka.network.cz/pipermail/bird-users/2024-December/017988.html

2025-01-13 16:03 UTC, PolynomialDivision commented
@tohojo I updated now to latest bird2 release.

2025-01-13 22:15 UTC, tohojo commented
Great, thanks!

2025-01-13 22:15 UTC, merged