olsrd: switch to firewall4
openwrt/routing pull request #812
Opened 2022-02-27 20:53 UTC by PolynomialDivision

Firewall4 uses nftables instead of iptables. Use iptables-nft for installing smart-gw-rules.

Fixes: #731 ("Certain upstream switch to firewall4 aka nftables instead of iptables")

2022-02-27 20:56 UTC, PolynomialDivision commented
I don't use smart gateway. Can anyone test?

2022-03-05 21:57 UTC, BKPepe requested changes

2022-03-05 21:57 UTC, BKPepe commented on olsrd/files/olsrd.sh
> +	IP4T="$( command -v iptables-nft )"
This change does not seems to be necessary.


```
root@turris:~# iptables
iptables v1.8.7 (nf_tables): no command specified
Try `iptables -h' or 'iptables --help' for more information.

```

2022-03-05 21:57 UTC, BKPepe commented on olsrd/Makefile
> +  DEPENDS:=+libpthread +libubus +iptables-nft +ip6tables-nft
This breaks compatibility with fw3.  By quick looking at commit https://github.com/openwrt/openwrt/commit/795e7155cbe3e78669f6821bf7aecb7c4e1e1afb it should be enough to add iptables and iptables6 w/o any suffix. :)

2022-03-05 21:57 UTC, BKPepe commented on olsrd/Makefile
> +  DEPENDS:=+libpthread +libubus +iptables-nft +ip6tables-nft
This breaks compatibility with fw3.  By quick looking at commit https://github.com/openwrt/openwrt/commit/795e7155cbe3e78669f6821bf7aecb7c4e1e1afb it should be enough to add iptables and iptables6 w/o any suffix. :)

2022-03-05 22:10 UTC, PolynomialDivision commented
Thanks! Changed it.

2022-03-05 22:16 UTC, BKPepe commented
Commit subject and commit description should be changed.

2022-03-06 07:44 UTC, PolynomialDivision commented
Did that.

2022-03-06 09:33 UTC, BKPepe commented
What about this? I wouldn't say I like copy&pasting commit messages from different commits and also the references always begin with 1 instead of 0.

```
The upcoming OpenWrt version (currently in the master branch) ships firewall4 by default [1], which uses nftables instead of iptables. 

Users might choose to use a compatible layer [2] with iptables-nft, decide which iptables they want to use, and make appropriate changes related to fw3/f4[3].

This package requires to use iptables (no matter which variant) for smart-gw-rules 

[1] https://github.com/openwrt/openwrt/commit/08d9f6e3020b4a149b2007b6ed7d684c49af9bbf

[2] https://www.redhat.com/en/blog/using-iptables-nft-hybrid-linux-firewall

[3] https://github.com/openwrt/openwrt/commit/795e7155cbe3e78669f6821bf7aecb7c4e1e1afb
```

Feel free to rewrite it based on your thoughts.

From my point of view, you should not use any **[Fixes:](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)** or any other keyword in the commit message since when you have it there and you will do force-push, you will only spam issue with mentions. You should rather put it to the pull request.

2022-03-06 13:11 UTC, PolynomialDivision commented
Sounds awesome! :)

2022-03-06 13:18 UTC, BKPepe approved these changes

2022-03-06 13:50 UTC, merged